#!/usr/bin/env bash
set -e

# Pull in the common helpers and reorient ourselves to the root of the repository.
source $(dirname $0)/common

# Builds and packages the kernel image, headers, and firmware.
${SCRIPT_DIR}/clean
${SCRIPT_DIR}/prepare
${SCRIPT_DIR}/build
${SCRIPT_DIR}/package
