#!/usr/bin/env bash
set -e

# If the first argument is the name of a build script, run the script.
#
# Otherwise, just pretend the argument(s) are a command unto themselves and execute them.
if [ -e ./scripts/$1 ]; then
    ./scripts/"$@"
else
    exec "$@"
fi

# Ensure all the files are owned by the UID/GID that `dapper` is running this build as.
chown -R $DAPPER_UID:$DAPPER_GID .
