#!/usr/bin/env bash
set -e

# Pull in the common helpers and reorient ourselves to the root of the repository.
source /source/scripts/common

# Build and package the kernel image, headers, and firmware first.
/source/scripts/ci

echo
echo "[*] Generating publish script for version '${VERSION}'..."

cat << EOF > ${OUTPUT_DIR}/publish.sh
#!/usr/bin/env bash
for artifact in \$(ls ./dist/artifacts) ; do
    hub release edit -m ${VERSION} -a ./dist/artifacts/\${artifact} ${VERSION}
done
EOF

chmod +x ${OUTPUT_DIR}/publish.sh

echo "Publish script complete! Run \`dist/publish.sh\` to upload the release to Github."
