#!/usr/bin/env bash
set -e

# Pull in the common helpers and reorient ourselves to the root of the repository.
source $(dirname $0)/common

# Build and package the kernel image, headers, and firmware first.
${SCRIPT_DIR}/ci

echo
echo "[*] Preparing publish assets for version '${VERSION}'..."

# Generate the SHA256 signatures for each tarball.
#
# We also spit this out in the release notes as some tools specifically check the notes for a Github
# release to find the checksums to verify assets after download.
pushd ${ARTIFACT_DIR}
sha256sum * > "${OUTPUT_DIR}/SHA256SUMS"
popd

ASSET_CHECKSUMS=$(cat ${OUTPUT_DIR}/SHA256SUMS)

# Build the release notes.
kernel_pkg=$(echo ${LINUX_SOURCE} | awk -F'=' '{print $1}')
kernel_base_version=$(echo ${LINUX_SOURCE} | awk -F'=' '{print $2}' | awk -F'-' '{print $1}')
kernel_abi_version=$(echo ${LINUX_SOURCE} | awk -F'=' '{print $2}' | awk -F'-' '{print $2}' | awk -F'.' '{print $1}')
kernel_version="${kernel_base_version}-${kernel_abi_version}-generic"
firmware_version=$(echo ${LINUX_FIRMWARE} | awk -F'=' '{print $2}')
cat << EOF > ${OUTPUT_DIR}/release-notes
## Details

**Kernel Version:** ${kernel_version} ([package search](https://packages.ubuntu.com/search?keywords=${kernel_pkg}&searchon=names))
**Firmware Version:** ${firmware_version} ([package search](https://packages.ubuntu.com/search?keywords=linux-firmware&searchon=names))

## Checksums

\`\`\`text
${ASSET_CHECKSUMS}
\`\`\`
EOF

echo "Release is ready for publish! Run the following command to upload the release to Github:"
echo
echo "  gh release -R tobz/k3os-reloaded-kernel create ${VERSION} --notes-file ./dist/release-notes ./dist/artifacts/*.xz ./dist/SHA256SUMS"
